### ISSUE TITLE
Make pngs error

### ISSUE THREAD

**Issue by Nezarn** [kanzure/pokecrystal#269]
nezarn@nezarn-virtual-machine:~/pokecrystal$ make pngs
find . -iname "*.lz"      -exec python extras/pokemontools/gfx.py unlz {} +
find . -iname "*.[12]bpp" -exec python extras/pokemontools/gfx.py png  {} +
Traceback (most recent call last):
  File "extras/pokemontools/gfx.py", line 1668, in <module>
    main()
  File "extras/pokemontools/gfx.py", line 1664, in main
    method(args.filenames)
  File "extras/pokemontools/gfx.py", line 1614, in convert_to_png
    export_2bpp_to_png(filename)
  File "extras/pokemontools/gfx.py", line 1135, in export_2bpp_to_png
    arguments.update(read_filename_arguments(filein))
  File "extras/pokemontools/gfx.py", line 1114, in read_filename_arguments
    w, h = argument.split('x')
ValueError: too many values to unpack
Makefile:63: recipe for target 'pngs' failed
make: *** [pngs] Error 1
nezarn@nezarn-virtual-machine:~/pokecrystal$

**Comment by yenatch** [comment]
https://github.com/kanzure/pokemon-reverse-engineering-tools/pull/87

**Comment by Nezarn** [comment]
that commit fixes it, thx.
